version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "chat"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"